-- Seed illustrative GP practices (Auckland-focused, multilingual).
-- Confirm details with clinics and https://www.healthpoint.co.nz before relying on them.

insert into public.gp_practices (
  name, address, suburb, city, region, phone, website, healthpoint_url,
  languages_spoken, accepting_new_patients, fee_adult, fee_child, fee_csc
) values
(
  'Greenwoods Medical Epsom',
  '6 Market Road, Epsom',
  'Epsom',
  'Auckland',
  'Auckland',
  '09 524 1940',
  'https://www.greenwoodsmedical.co.nz',
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/greenwoods-medical-epsom/',
  array['english','mandarin']::text[],
  true,
  18.50,
  13.00,
  12.50
),
(
  'Eastcare Botany',
  '588 Chapel Road, Botany',
  'Botany',
  'Auckland',
  'Auckland',
  '09 277 1666',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/eastcare-botany/',
  array['english','mandarin','cantonese']::text[],
  true,
  19.00,
  13.50,
  13.00
),
(
  'Ascot White Cross',
  '90 Ascot Avenue, Remuera',
  'Remuera',
  'Auckland',
  'Auckland',
  '09 520 9611',
  'https://www.whitecross.co.nz',
  'https://www.healthpoint.co.nz/gp/urgent-care/auckland/ascot-white-cross/',
  array['english','mandarin']::text[],
  false,
  85.00,
  45.00,
  null
),
(
  'Highland Park Medical Centre',
  '77 Aviemore Drive, Highland Park',
  'Highland Park',
  'Auckland',
  'Auckland',
  '09 534 5252',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/highland-park-medical-centre/',
  array['english','mandarin','korean']::text[],
  true,
  17.50,
  12.00,
  12.00
),
(
  'Flat Bush Medical Centre',
  '2 Te Irirangi Drive, Flat Bush',
  'Flat Bush',
  'Auckland',
  'Auckland',
  '09 274 7828',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/flat-bush-medical-centre/',
  array['english','mandarin','cantonese']::text[],
  true,
  18.00,
  13.00,
  12.50
),
(
  'Lincoln Road Medical Centre',
  '159 Lincoln Road, Henderson',
  'Henderson',
  'Auckland',
  'Auckland',
  '09 835 0550',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/lincoln-road-medical-centre/',
  array['english','mandarin']::text[],
  true,
  17.00,
  11.50,
  11.50
),
(
  'Northcare Medical Centre',
  '194 Wairau Road, Wairau Valley',
  'Wairau Valley',
  'Auckland',
  'Auckland',
  '09 443 3810',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/northcare-medical-centre/',
  array['english','mandarin','korean']::text[],
  true,
  18.50,
  13.00,
  12.50
),
(
  'Albany Family Medical Centre',
  '2/100 Don McKinnon Drive, Albany',
  'Albany',
  'Auckland',
  'Auckland',
  '09 415 8290',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/albany-family-medical-centre/',
  array['english','mandarin','cantonese']::text[],
  true,
  19.50,
  14.00,
  13.50
),
(
  'East Tamaki Healthcare',
  '188 Harris Road, East Tamaki',
  'East Tamaki',
  'Auckland',
  'Auckland',
  '09 274 0100',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/east-tamaki-healthcare/',
  array['english','mandarin']::text[],
  false,
  20.00,
  14.50,
  14.00
),
(
  'Royal Oak Family Medical',
  '785 Manukau Road, Royal Oak',
  'Royal Oak',
  'Auckland',
  'Auckland',
  '09 625 7444',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/royal-oak-family-medical/',
  array['english','mandarin']::text[],
  true,
  18.00,
  13.00,
  12.50
),
(
  'New Lynn Medical Centre',
  '3058 Great North Road, New Lynn',
  'New Lynn',
  'Auckland',
  'Auckland',
  '09 826 0088',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/new-lynn-medical-centre/',
  array['english','mandarin','cantonese']::text[],
  true,
  17.50,
  12.50,
  12.00
),
(
  'Panmure Medical Centre',
  '6/6 Queens Road, Panmure',
  'Panmure',
  'Auckland',
  'Auckland',
  '09 570 0434',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/panmure-medical-centre/',
  array['english','mandarin']::text[],
  true,
  16.50,
  11.00,
  11.00
),
(
  'Takanini Family Doctors',
  '106 Great South Road, Takanini',
  'Takanini',
  'Auckland',
  'Auckland',
  '09 299 9299',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/takanini-family-doctors/',
  array['english','mandarin','korean']::text[],
  true,
  18.00,
  12.50,
  12.00
),
(
  'Pukekohe Family Health',
  '10 West Street, Pukekohe',
  'Pukekohe',
  'Auckland',
  'Auckland',
  '09 238 7788',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/pukekohe-family-health/',
  array['english','mandarin']::text[],
  true,
  17.00,
  11.50,
  11.50
),
(
  'Orewa Medical Centre',
  '50 Moana Avenue, Orewa',
  'Orewa',
  'Auckland',
  'Auckland',
  '09 426 4426',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/orewa-medical-centre/',
  array['english','mandarin']::text[],
  false,
  19.00,
  13.50,
  13.00
),
(
  'Wairau Park Medical',
  '17 Link Drive, Wairau Valley',
  'Wairau Valley',
  'Auckland',
  'Auckland',
  '09 443 4626',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/wairau-park-medical/',
  array['english','mandarin','cantonese']::text[],
  true,
  18.50,
  13.00,
  12.50
),
(
  'St Lukes Family Medical',
  '80 St Lukes Road, Mount Albert',
  'Mount Albert',
  'Auckland',
  'Auckland',
  '09 845 9811',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/st-lukes-family-medical/',
  array['english','mandarin']::text[],
  true,
  19.00,
  13.50,
  13.00
),
(
  'Onehunga Medical Centre',
  '301 Onehunga Mall, Onehunga',
  'Onehunga',
  'Auckland',
  'Auckland',
  '09 636 9164',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/onehunga-medical-centre/',
  array['english','mandarin']::text[],
  true,
  17.50,
  12.00,
  12.00
),
(
  'Mangere Bridge Medical',
  '123 Coronation Road, Mangere Bridge',
  'Mangere Bridge',
  'Auckland',
  'Auckland',
  '09 636 0494',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/mangere-bridge-medical/',
  array['english','mandarin','cantonese']::text[],
  true,
  16.00,
  10.50,
  10.50
),
(
  'Howick Village Doctors',
  '29 Picton Street, Howick',
  'Howick',
  'Auckland',
  'Auckland',
  '09 534 5252',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/howick-village-doctors/',
  array['english','mandarin']::text[],
  true,
  18.50,
  13.00,
  12.50
),
(
  'Sunnyhills Medical Centre',
  '684 Pakuranga Road, Pakuranga',
  'Pakuranga',
  'Auckland',
  'Auckland',
  '09 576 5222',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/sunnyhills-medical-centre/',
  array['english','mandarin','korean']::text[],
  true,
  18.00,
  12.50,
  12.00
),
(
  'Glenfield Medical Centre',
  '385 Glenfield Road, Glenfield',
  'Glenfield',
  'Auckland',
  'Auckland',
  '09 444 0777',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/glenfield-medical-centre/',
  array['english','mandarin']::text[],
  false,
  17.50,
  12.00,
  12.00
),
(
  'Torbay Medical Centre',
  '865 Beach Road, Torbay',
  'Torbay',
  'Auckland',
  'Auckland',
  '09 473 0417',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/torbay-medical-centre/',
  array['english','mandarin']::text[],
  true,
  18.00,
  12.50,
  12.50
),
(
  'Milford Medical',
  '181 Kitchener Road, Milford',
  'Milford',
  'Auckland',
  'Auckland',
  '09 489 5011',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/milford-medical/',
  array['english','mandarin','cantonese']::text[],
  true,
  20.00,
  14.50,
  14.00
),
(
  'Newmarket Medical',
  '55 Carlton Gore Road, Newmarket',
  'Newmarket',
  'Auckland',
  'Auckland',
  '09 529 9111',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/auckland/newmarket-medical/',
  array['english','mandarin']::text[],
  true,
  19.50,
  14.00,
  13.50
),
(
  'Wellington Central Medical',
  '120 Featherston Street, Wellington Central',
  'Wellington Central',
  'Wellington',
  'Wellington',
  '04 499 9999',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/wellington/wellington-central-medical/',
  array['english','mandarin']::text[],
  true,
  19.00,
  13.50,
  13.00
),
(
  'Christchurch East Care',
  '1000 Ferry Road, Ferrymead',
  'Ferrymead',
  'Christchurch',
  'Canterbury',
  '03 384 1000',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/christchurch/christchurch-east-care/',
  array['english','korean']::text[],
  true,
  18.50,
  13.00,
  12.50
),
(
  'Hamilton North Medical',
  '5 Norton Road, Frankton',
  'Frankton',
  'Hamilton',
  'Waikato',
  '07 838 3838',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/hamilton/hamilton-north-medical/',
  array['english','mandarin']::text[],
  true,
  17.50,
  12.00,
  12.00
),
(
  'Tauranga Family Health',
  '123 Cameron Road, Tauranga Central',
  'Tauranga Central',
  'Tauranga',
  'Bay of Plenty',
  '07 578 7788',
  null,
  'https://www.healthpoint.co.nz/gp/medical-clinic/tauranga/tauranga-family-health/',
  array['english','mandarin','cantonese']::text[],
  true,
  18.00,
  12.50,
  12.50
);
